<FeatureButton>
	font_size: dp(120)
	line_width: dp(7)
	
<HomePageView>:
	BoxLayout:
		padding: [dp(50), dp(50)]				
		orientation: 'vertical'
		GridLayout:
			spacing: dp(60)
			rows: 2
			cols: 3
			FeatureButton:
				text: '\357\203\244'
			FeatureButton:
				text: '\357\202\200'
			FeatureButton:
				text: '\357\202\205'
			FeatureButton:
				text: '\357\200\230'
			FeatureButton:
				text: '\357\201\204'
			
