<FeatureButton>
	
<HomePageView>:
	BoxLayout:
		padding: [dp(50), dp(50)]				
		orientation: 'vertical'
		GridLayout:
			spacing: dp(60)
			rows: 2
			cols: 3
			FeatureButton:
				icon: '\357\203\244'
				title: 'Dashboard'
			FeatureButton:
				icon: '\357\202\200'
				title: 'Analysis'
			FeatureButton:
				icon: '\357\202\205'
				title: 'Configuration'
			FeatureButton:
				icon: '\357\200\230'
				title: 'Race Tracks'
			FeatureButton:
				icon: '\357\201\204'
				title: 'Channels'
			
