#:kivy 1.8.0


<BluetoothTelemetryView>:
	orientation: 'vertical'
	SettingsView:
		rcid: 'btenable'
		label_text: 'Enable Bluetooth channels'
		help_text: 'Enable Bluetooth connectivity'
		size_hint_y: 0.3
	HLineSeparator:
	BoxLayout:
		orientation: 'vertical'
        BoxLayout:
        	orientation: 'horizontal'
		    Label:
		        text: 'Bluetooth device settings'
	        Button:
	        	text: 'Configure'






