#:kivy 1.8.0


<BluetoothTelemetryView>:
	orientation: 'vertical'
	SettingsView:
		size_hint_y: 0.25
		rcid: 'btenable'
		label_text: 'Enable Bluetooth channels'
		help_text: 'Enable Bluetooth connectivity'
	HLineSeparator:
		size_hint_y: 0.1
	SettingsView:
		size_hint_y: 0.25
		rcid: 'btconfig'
		label_text: 'Configure Bluetooth device'
		help_text: 'Configure Bluetooth device username and password. This should be used while connected via USB'
	Label:
		size_hint_y: 0.4

	



