#:kivy 1.8.0



<SettingsView>:

<SettingsViewSwitch>:
	size_hint: (1.0, 0.2)
	spacing: 40
	orientation: 'vertical'
	BoxLayout:
		rcid: 'fieldContainer'
		orientation: 'horizontal'
		FieldLabel:
			rcid: 'fieldLabel'
			halign: 'right'
			font_size: 20
			text: ''
		Switch:
			rcid: 'settingsCtrl'
			on_active: root.on_switch_active(*args)
			
	HelpLabel:
		rcid: 'helpLabel'
		halign: 'left'
		text: ''

	