#ifndef COMMON_EVENTS_H_
#define COMMON_EVENTS_H_

#include "wx/wxprec.h"

DECLARE_EVENT_TYPE ( OPTIONS_CHANGED_EVENT, -1 )
DECLARE_EVENT_TYPE ( CONFIG_CHANGED_EVENT, -1 )
DECLARE_EVENT_TYPE ( CONFIG_STALE_EVENT, -1 )
DECLARE_EVENT_TYPE ( WRITE_CONFIG_EVENT, -1 )

enum{
		CONFIG_CHANGED 	= wxID_HIGHEST + 80000,
		OPTIONS_CHANGED,
		CONFIG_STALE,
		WRITE_CONFIG
};

#endif /*EVENTS_H_*/
