#ifndef MEMORY_DEVICE_PAGE_SIZE_H_
#define MEMORY_DEVICE_PAGE_SIZE_H_
#include "board.h"

#define MEMORY_START_ADDRESS   AT91C_IFLASH
#define MEMORY_SIZE            AT91C_IFLASH_SIZE
#define MEMORY_PAGE_SIZE       AT91C_IFLASH_PAGE_SIZE
#define MEMORY_PAGE_SIZE_32    (MEMORY_PAGE_SIZE / 4)

#endif /* MEMORY_DEVICE_PAGE_SIZE_H_ */
