#include "commonEvents.h"


DEFINE_EVENT_TYPE ( OPTIONS_CHANGED_EVENT )
DEFINE_EVENT_TYPE ( CONFIG_CHANGED_EVENT )
DEFINE_EVENT_TYPE ( CONFIG_STALE_EVENT )
DEFINE_EVENT_TYPE ( WRITE_CONFIG_EVENT )
